name: flutter_webviewe
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

  flutter_webview_plugin: 0.3.11
  webview_flutter: 0.3.21


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
